"""LLM Provider abstraction layer for AdverSight.

Decouples the adversarial testing engine and LLM judge from specific provider
implementations. Supports Gemini (via official REST API) and mock providers for testing.
API keys are loaded strictly from environment variables (e.g. GEMINI_API_KEY).
"""
from __future__ import annotations

from abc import ABC, abstractmethod
import logging
import os
from typing import Any

import httpx

from app.util.trace_commons import LLMClient

logger = logging.getLogger(__name__)


class LLMProvider(ABC):
    """Abstract interface for LLM text generation."""

    @abstractmethod
    def generate(self, prompt: str, system: str | None = None) -> str:
        """Generate a response given a user prompt and optional system instructions.

        Must raise an exception on failure so caller can fall back to deterministic templates.
        """
        ...


class GeminiProvider(LLMProvider):
    """Google Gemini API provider using official Generative Language REST endpoints.

    Zero hardcoded credentials. Reads GEMINI_API_KEY from environment or constructor.
    """

    DEFAULT_MODEL = "gemini-1.5-flash"
    BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models"

    def __init__(
        self,
        api_key: str | None = None,
        model: str = DEFAULT_MODEL,
        timeout: float = 15.0,
    ) -> None:
        self.api_key = api_key or os.environ.get("GEMINI_API_KEY")
        self.model = model
        self.timeout = timeout

    def generate(self, prompt: str, system: str | None = None) -> str:
        if not self.api_key:
            raise RuntimeError("GEMINI_API_KEY is not set in environment.")

        url = f"{self.BASE_URL}/{self.model}:generateContent?key={self.api_key}"
        payload: dict[str, Any] = {
            "contents": [
                {
                    "parts": [{"text": prompt}]
                }
            ],
            "generationConfig": {
                "temperature": 0.7,
                "maxOutputTokens": 500,
            },
        }

        if system:
            payload["system_instruction"] = {
                "parts": [{"text": system}]
            }

        try:
            with httpx.Client(timeout=self.timeout) as client:
                resp = client.post(url, json=payload)
                resp.raise_for_status()
                data = resp.json()

            candidates = data.get("candidates", [])
            if not candidates:
                raise RuntimeError("No candidate generated by Gemini API.")

            parts = candidates[0].get("content", {}).get("parts", [])
            if not parts:
                raise RuntimeError("Empty response content from Gemini.")

            return str(parts[0].get("text", "")).strip()
        except Exception as exc:
            logger.warning("Gemini generation failed: %s", exc)
            raise RuntimeError(f"Gemini API error: {exc}") from exc


class MockLLMProvider(LLMProvider):
    """Deterministic mock LLM provider for unit tests and local simulation."""

    def __init__(self, response: str | Exception = "Mock adversarial prompt") -> None:
        self.response = response
        self.call_history: list[dict[str, str | None]] = []

    def generate(self, prompt: str, system: str | None = None) -> str:
        self.call_history.append({"prompt": prompt, "system": system})
        if isinstance(self.response, Exception):
            raise self.response
        return self.response


def get_llm_provider() -> LLMProvider | None:
    """Factory returning configured LLMProvider based on environment."""
    api_key = os.environ.get("GEMINI_API_KEY")
    if api_key:
        return GeminiProvider(api_key=api_key)
    return None
